### PR TITLE
Added solutions to all problems

### PR DESCRIPTION
**Pull request by Fay2416**
Added solutions to all problems
Fay Submission

### CODE REVIEW

**Comment by CodelineGitHub** [comment]
Dear Applicant,
Please comment below the following details.
Name:
Email:
Phone Number:
 
Thanks.

**Comment by CodelineGitHub** [comment]
Dear Applicant,
Please comment below the following details.
Name:
Email:
Phone Number:
 
Thanks.

**Comment by Fay2416** [comment]
Name: Fay Saleh Al-Qassimi
Email Address: fay_2416@hotmail.com
Phone Number: 94021782

**Comment by Fay2416** [comment]
Name: Fay Saleh Al-Qassimi
Email Address: fay_2416@hotmail.com
Phone Number: 94021782

**Pull request closed without merging**
